### ISSUE TITLE
[Request] Turkey Startup Investing list 

### ISSUE THREAD

**Issue by ramazansancar** [KHARAPSY/web_scrape#1]
List:
- Aslanoba Capital
- Bic Angel Investment
- Esas Holding
- Galata Business Angel
- Inovent
- Inventram
- Istanbul Startup Angel
- İş Girişim Sermayesi
- Keiretsu Forum Turkey
- Kobi Girişim Sermayesi
- Rhea Girişim
- Şirket Ortağım Melek Yatırım Ağı
- https://www.isgirisim.com.tr/yatirimlarimiz
- Hedef Girişim:
  - https://hedefgirisim.com.tr/tr/mevcutyatirimlar/
  - https://hedefgirisim.com.tr/tr/tamamlanmisyatirimlar/
- https://startupfon.com/startups
- https://startupborsa.com/
- https://212.vc/
- https://500.co/
- https://angeleffect.co/
- https://www.bogaziciventures.com/
- https://www.apyventures.com/
- https://arzportfoy.com/
- https://finberg.com.tr/
- https://galatabusinessangels.com/tr/
- https://geometryventure.dev/
- https://hivc.io/
- https://www.inveo.co/
- https://www.qnbeyondventures.com/
- https://www.scalexventures.com/
- https://sirketortagim.com/
- https://www.tarvenn.com/
- https://www.techone.vc/
- https://www.twozero.vc/
- https://www.weplayventures.com/
- https://yildizteknogsyo.com/yatirimlarimiz/

**Comment by KHARAPSY** [comment]
Hi, I not sure how can i help here?

**Comment by ramazansancar** [comment]
You can use the list to add new resource providers. They offer a list of startups located in Türkiye
